package com.akibahub.audit.model;

public enum EventType {
    // Auth events
    AUTH_LOGIN,
    AUTH_LOGOUT,
    AUTH_TOKEN_REFRESHED,

    // Personal savings events
    PERSONAL_DEPOSIT_INITIATED,
    PERSONAL_DEPOSIT_COMPLETED,
    PERSONAL_DEPOSIT_FAILED,
    PERSONAL_WITHDRAWAL_INITIATED,
    PERSONAL_WITHDRAWAL_COMPLETED,

    // Group events
    GROUP_CREATED,
    GROUP_UPDATED,
    GROUP_DELETED,
    MEMBER_JOINED,
    MEMBER_REMOVED,
    MEMBER_ROLE_CHANGED,
    INVITE_CODE_GENERATED,

    // Group finance events
    GROUP_CONTRIBUTION_INITIATED,
    GROUP_CONTRIBUTION_COMPLETED,
    GROUP_CONTRIBUTION_FAILED,

    // Proposal events
    PROPOSAL_CREATED,
    PROPOSAL_CANCELLED,
    PROPOSAL_APPROVED,
    PROPOSAL_REJECTED,
    PROPOSAL_EXPIRED,

    // Vote events
    VOTE_CAST,
    VOTE_CHANGED,

    // Withdrawal events
    WITHDRAWAL_INITIATED,
    WITHDRAWAL_COMPLETED,
    WITHDRAWAL_FAILED,

    // Payment events
    PAYMENT_INITIATED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    PAYMENT_CALLBACK_RECEIVED
}
